# Generated by Django 5.2.7 on 2025-10-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
    ]
