# Generated by Django 5.2.7 on 2025-10-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporter', '0004_alter_incident_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
